/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/octopus.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/octopus.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Object_4">
          <primitive object={nodes._rootJoint} />
          <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.octopus_uu} skeleton={nodes.Object_10.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/octopus.glb')
